// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6z-_i2XV6qEQa0UjASzDFfqDOum0_TO8',
    appId: '1:1071445998985:web:f13641556e592a3c08f558',
    messagingSenderId: '1071445998985',
    projectId: 'githubpro-3cba1',
    authDomain: 'githubpro-3cba1.firebaseapp.com',
    storageBucket: 'githubpro-3cba1.appspot.com',
    measurementId: 'G-BXL5ZN8FCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUuyUdSLbknEIumGBBq3a_CFijzRcDU2M',
    appId: '1:1071445998985:android:9de8ec2da976ff7208f558',
    messagingSenderId: '1071445998985',
    projectId: 'githubpro-3cba1',
    storageBucket: 'githubpro-3cba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABchu3OsTpbSlGQzAG0bx3LbfVm_YzYow',
    appId: '1:1071445998985:ios:aebc13804b463ccb08f558',
    messagingSenderId: '1071445998985',
    projectId: 'githubpro-3cba1',
    storageBucket: 'githubpro-3cba1.appspot.com',
    iosBundleId: 'com.example.githubpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABchu3OsTpbSlGQzAG0bx3LbfVm_YzYow',
    appId: '1:1071445998985:ios:6a6b3c773db5adce08f558',
    messagingSenderId: '1071445998985',
    projectId: 'githubpro-3cba1',
    storageBucket: 'githubpro-3cba1.appspot.com',
    iosBundleId: 'com.example.githubpro.RunnerTests',
  );
}
